Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from myst_nb import glue

def make_axes():
    
    fig, axes = plt.subplots(1, 2, figsize=(9.5,4))
    fig.subplots_adjust(wspace=0.5)
    fig.text(0.5, 0.5, "$T$", fontsize=20, ha="center")
    fig.text(0.5, 0.4, "$\longrightarrow$", fontsize=30, ha="center")
    for ax in axes:
        ax.set_xlim(-2, 2)
        ax.set_ylim(-2, 2)
        ax.set_xticks([-2, -1, 0, 1, 2])
        ax.set_yticks([-2, -1, 0, 1, 2])
        ax.grid()
        ax.set_axisbelow(True)
    
    return fig, axes

def plot_vector(ax, x, y):
    ax.arrow(0, 0, x, y, width=0.03, color="black", length_includes_head=True)
    
def add_text(ax, x, y, s):
    ax.text(x, y, s, fontsize=16)
------------------

----- stderr -----
<>:10: SyntaxWarning: invalid escape sequence '\l'
<>:10: SyntaxWarning: invalid escape sequence '\l'
/var/folders/c3/n_d053q94csd92r2k5pbc0cw0000gp/T/ipykernel_249/1585843601.py:10: SyntaxWarning: invalid escape sequence '\l'
  fig.text(0.5, 0.4, "$\longrightarrow$", fontsize=30, ha="center")
/var/folders/c3/n_d053q94csd92r2k5pbc0cw0000gp/T/ipykernel_249/1585843601.py:10: SyntaxWarning: invalid escape sequence '\l'
  fig.text(0.5, 0.4, "$\longrightarrow$", fontsize=30, ha="center")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmyst_nb[39;00m [38;5;28;01mimport[39;00m glue

[0;31mModuleNotFoundError[0m: No module named 'numpy'

