Traceback (most recent call last):
  File "/home/pete/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/pete/.local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/pete/.local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/pete/.local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/pete/.local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/pete/.local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/pete/.local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n = np.arange(1, 100, 1)
a = (n - 1) / (n + 1)
plt.scatter(1/n, a)

plt.grid()
plt.xlabel("1/n")
plt.ylable("(n-1)/(n+1)")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[3], line 7[0m
[1;32m      5[0m plt[38;5;241m.[39mgrid()
[1;32m      6[0m plt[38;5;241m.[39mxlabel([38;5;124m"[39m[38;5;124m1/n[39m[38;5;124m"[39m)
[0;32m----> 7[0m [43mplt[49m[38;5;241;43m.[39;49m[43mylable[49m([38;5;124m"[39m[38;5;124m(n-1)/(n+1)[39m[38;5;124m"[39m)

[0;31mAttributeError[0m: module 'matplotlib.pyplot' has no attribute 'ylable'
AttributeError: module 'matplotlib.pyplot' has no attribute 'ylable'

